= Code of Conduct
RogueScholar <RogueScholar@users.noreply.github.com>

:sectanchors:
:toc: macro
:toclevels: 1

////
SPDX-FileCopyrightText: © 2026, Peter J. Mello <admin@petermello.net>
SPDX-License-Identifier: CC-BY-SA-4.0
////

// Metadata:
:description: Standards of conduct for participation in open-source repository
:keywords: Netboot.xyz, PXE, iPXE, Clonezilla, Grml, Parted Magic
:revdate: 2026-08-29
:revnumber: 1.1.0
// Refs:
:button-ccbysa4: https://licensebuttons.net/l/by-sa/4.0/88x31.png
:url-ccbysafour: https://creativecommons.org/licenses/by-sa/4.0/
:url-ccfaq: https://www.contributor-covenant.org/faq
:url-cchome: https://www.contributor-covenant.org/
:url-ccl10n: https://www.contributor-covenant.org/translations
:url-cclogo: https://www.contributor-covenant.org/images/logo-inverted.svg
:url-ccthreeoh: https://www.contributor-covenant.org/version/3/0
:url-ladder: {url-mozcoc}/blob/master/code-of-conduct-enforcement/consequence-ladder.md
:url-mozcoc: https://github.com/mozilla/inclusion
:url-oeshome: https://ethicalsource.dev/

== 🤝 Pledge

We as members, contributors, and leaders pledge to make participation in our
community a harassment-free experience for everyone, regardless of age, body
size, visible or invisible disability, ethnicity, sex characteristics, gender
identity and expression, level of experience, education, socio-economic status,
nationality, personal appearance, race, religion or sexual identity and
orientation.

We pledge to act and interact in ways that contribute to an open, welcoming,
diverse, inclusive, and healthy community.

== 🎏 Standards

=== 👍 Acceptable behavior

Examples of behavior that contributes to a positive environment for our
community include:

* Demonstrating empathy and kindness toward other people
* Being respectful of differing opinions, viewpoints and experiences
* Giving and gracefully accepting constructive feedback
* Accepting responsibility and apologizing to those affected by our mistakes,
and learning from the experience
* Focusing on what is best not just for us as individuals, but for the overall
community

=== 👎 Unacceptable behavior

Examples of unacceptable behavior include:

* The use of sexualized language or imagery, and sexual attention or advances of
any kind
* Trolling, insulting or derogatory comments, and personal or political attacks
* Public or private harassment
* Publishing others' private information, such as a physical or email address,
without their explicit permission
* Other conduct which could reasonably be considered inappropriate in a
professional setting

== 🔬 Scope

This Code of Conduct applies within all community spaces, and also applies when
an individual is officially representing the community in public spaces.
Examples of representing our community include using official email addresses,
posting with official social media accounts, or acting as an appointed
representative at online or offline events.

== 🔨 Enforcement

Instances of abusive, harassing or otherwise unacceptable behavior may be
reported to the community leaders responsible for enforcement at the
repository's GitHub Discussions tab. All complaints will be reviewed and
investigated promptly and fairly.

All community leaders are obligated to respect the privacy and security of the
reporter of any incident.

=== 🧑 Responsibility to act

Community leaders are responsible for clarifying and enforcing our standards of
acceptable behavior and will take decisive, appropriate and fair corrective
action in response to any behavior that they deem inappropriate, threatening,
offensive or harmful.

Community leaders have the right and responsibility to remove, edit, or reject
comments, commits, code, wiki edits, issue reports, and other contributions that
do not conform to the standards defined in this Code of Conduct, and will
communicate their reasons for moderation decisions when appropriate.

=== 🪜 Enforcement ladder

Community leaders will follow these Community Impact Guidelines in determining
the consequences for any action they deem in violation of this Code of Conduct:

==== Step 1️⃣: Correction

*Community Impact*: Use of inappropriate language or other behavior deemed
unprofessional or unwelcome in the community.

*Consequence*:

* A private, written warning from community leaders, providing clarity around
the nature of the violation and an explanation of why the behavior was
deemed inappropriate.
 ** A public apology may be requested.

==== Step 2️⃣: Warning

*Community Impact*: A violation through a single incident or series of
actions.

*Consequence*:

. A warning with consequences for continued behavior.
. No interaction with the people involved or affected, including unsolicited
interaction with those enforcing the Code of Conduct, for a finite period of
time. This includes avoiding interactions in community spaces, as well as
external channels like social media.
 ** Violating these terms may lead to a temporary or permanent ban.

==== Step 3️⃣: Temporary Ban

*Community Impact*: A serious violation of community standards, including
sustained inappropriate behavior.

*Consequence*:

. A temporary ban from any sort of interaction or public communication with the
community for a specified period of time.
. No public or private interaction with the people involved or affected,
including unsolicited interaction with those enforcing the Code of Conduct,
is allowed during this period.
 ** Violating these terms may lead to a permanent ban.

==== Step 4️⃣: Permanent Ban

*Community Impact*: Demonstrating a pattern of violation of community
standards, including sustained inappropriate behavior,  harassment of an
individual or aggression/disparagement toward entire classes of individuals.

*Consequence*: A permanent ban from any sort of public interaction within
the community.

== 📜 Attribution and licensing

[image:{url-cclogo}[Contributor Covenant logo,128]]{url-cchome}[homepage]
This document has been adapted from version 3.0 of the Contributor Covenant
(official version at {url-ccthreeoh}[contributor-covenant.org/version/3/0]),
published under the stewardship of the {url-oeshome}[Organization for Ethical
Source], and licensed according to the grants and restrictions set forth in the
{url-ccbysafour}[Creative Commons Attribution-ShareAlike 4.0 International
Public License] (CC-BY-SA-4.0).

image::{button-ccbysa4}[CC-BY-SA-4.0,link={url-ccbysafour}]

The enforcement ladder is adapted from the {url-ladder}[Consequence Ladder]
developed and used by Mozilla's {url-mozcoc}[Code of Conduct team].

== 🔗 External links

* {url-cchome}[Contributor Covenant official website]
 ** {url-ccfaq}[FAQ]
 ** {url-ccl10n}[Official translations]
