= Personal set of rescue tools: Live-booted by netboot.xyz
RogueScholar <RogueScholar@users.noreply.github.com>

:figure-caption!:
:imagesdir: images
:sectanchors:
:source-highlighter: highlight.js
:toc!:

////
SPDX-FileCopyrightText: © 2019–2026, RogueScholar <RogueScholar@users.noreply.github.com>
SPDX-License-Identifier: CC0-1.0
////

// Metadata:
:description: README page for repository containing a custom Netboot.xyz implementation
:keywords: Netboot.xyz, PXE, iPXE, Clonezilla, Grml, Parted Magic
:revdate: 2026-08-29
:revnumber: 2.0.0
// Refs:
:activity-badge: https://img.shields.io/github/last-commit/RogueScholar/netboot.xyz-custom?style=plastic&logo=ticktick&logoColor=white&logoSize=auto&cacheSeconds=3600
:apache-way: ASF_apacheway_badge-purple.webp
:commit-log: https://github.com/RogueScholar/netboot.xyz-custom/commits/main/
:keybase-id: https://keybase.io/rscholar
:keybase-badge: https://img.shields.io/keybase/pgp/rscholar?style=plastic&logo=keybase&logoColor=white&logoSize=auto&label=keybase&labelColor=4a62e1&color=white&cacheSeconds=3600
:license-badge: https://img.shields.io/badge/license-Apache\--2.0-29265e?style=plastic&logo=apache&logoColor=ef9b2e&logoSize=auto&labelColor=dimgray&cacheSeconds=7200
:nbxyz-logo: nbxyz_logo_name.png
:reuse-badge: https://api.reuse.software/badge/github.com/RogueScholar/netboot.xyz-custom
:reuse-info: https://api.reuse.software/info/github.com/RogueScholar/netboot.xyz-custom
:url-apache: https://www.apache.org/licenses/LICENSE-2.0
:url-project: https://netboot.xyz/

image:{reuse-badge}[alt="REUSE status",height=20,width=110,link={reuse-info}]
&#x2003;
image:{activity-badge}[alt"Last commit date",height=20,link={commit-log}]
&#x2003;
image:{license-badge}[alt=License,height=20,width=153,link={url-apache}]
&#x2003;
image:{keybase-badge}[alt="Keybase PGP",height=20,width=218,link={keybase-id}]

''''

.*Featuring cloud booting into Clonezilla, Grml and Parted Magic!*
image::{nbxyz-logo}["Netboot.xyz logo",360,235,align=center]

== What this is

[.lead.text-justify]
Soon, we'll do a quick review of the foundational knowledge needed to understand
how this works, but for now we'll speak in generalities. The *Preboot eXecution
Environment*, or *PXE* (typically pronouned _"Pixie"_) is a specification for
booting computers not from files read over a local data bus, but downloaded over
a network connection, stored in volatile memory (RAM) and if the download
succeeds, run from memory as well. It was however mostly a business tool tightly
coupled with the advent of the first data centers, and barely any effort was
expended to share its vast potential to everyday users, hobbyists and power
users. This gave rise to first the gPXE open-source implementation, and later to
its modern-day successor, *iPXE*. They wrote implementations that could be
flashed onto consumer network adapters and executed by consumer-grade
mainboards. It filled such an obvious need that for at least a dozen years (as
of this writing in 2026), if you use an upper-mid-tier computer from a major
brand, it's more likely than not that iPXE was included in your network adapter
firmware when you bought it.net

[.lead.text-justify]
The reason that it still hasn't become an everyday tool and point of reference
to the common man is that there are some baked-in handicaps to how it's used.
These all relate to the manner by which you inform the system of what files you
want it to retrieve, where on the network to acquire them from and with which
options to execute them. Since all of this occurs prior to the system firmware
reaching a READY state, your only conversation partner is the network interface
and a console interface that can often make DOS 6.0 appear quite sophisticated
by comparison. And now we've arrived at the reason for having gathered here:
*Netboot.xyz*. [small]#_[cue angelic choir in unison, "Ahhhh"]_#

== Usage

=== Install prerequisites

To _use_ this repository, you need only to cause your system to load Netboot.xyz
through its native iPXE implementation, or boot your system using one of the
many one-time boot methods documented at the Netbook.xyz project web site (and
elsewhere all over the internet).

install the base netboot.xyz image, a Keybase account and the Keybase client.

* https://netboot.xyz/[Netboot.xyz Home Page]
* https://keybase.io/[Join Keybase]
* https://keybase.io/download[Install the Keybase client]

== Chainloading

If you just want to boot your iPXE-enabled system using one of the utilities in
the menu, you need only navigate to an iPXE shell prompt and issue this command:

[source,sh]
----
chain --autofree https://raw.githubusercontent.com/RogueScholar/netboot.xyz-custom/master/custom.ipxe
----

== License

[.left.text-center]
image::{apache-way}["The Apache Way",80,80]

The terms of the {url-apache}[Apache License, version 2.0], govern the
acceptable use of the contents of this repository, unless otherwise specified
within a specific file.

'''

.Colophon
[%collapsible]
====
Document Version: {revnumber}

Last Updated: {revdate}
====
